### ISSUE TITLE
Fix JPA entities

### ISSUE THREAD

**Issue by anasabau** [anasabau/FlightManager#1]
Tables will not be created or populated by JPA.

**Comment by stoiandan** [comment]
Fixed, problem was that inside glassfish-resources.xml, file used by the persistence xml, the datasource-class attribute was set to _org.mariadb.jdbc.Driver_ instead of _org.mariadb.jdbc.MariaDbDataSource_
also to the jdbc URL, at the end we needed to specify the concrete database name, which is _flight_manager_
